version: "3"

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    hostname: redis
    networks:
      - webnet

  app:
    build: .
    ports:
      - "3000:3000"
    command: "npm start"
    networks:
      - webnet

networks:
  webnet:
